/**
 * Spain administrative geography dataset.
 *
 * Sources:
 *  - Geometry: martgnz/es-atlas (IGN-derived TopoJSON), MIT License
 *  - Administrative codes: INE (Instituto Nacional de Estadística) via
 *    CodeForSpain/ds-organizacion-administrativa (2026-01-01 reference)
 *  - Capital coordinates: manually verified authoritative coordinates
 *  - Flags: Wikimedia Commons (public domain / Creative Commons)
 *
 * Dataset identifiers use ISO 3166-2:ES subdivision codes.
 * INE 2-digit codes map to ISO codes via CCAA_INE_TO_ISO and PROVINCE_INE_TO_ISO.
 *
 * Hierarchy:
 *   Spain
 *   └─ Autonomous Community (ES-AN, ES-AR, ... ES-CE, ES-ML)
 *      └─ Province (ES-VI, ES-AB, ... ES-Z)
 *         └─ Capital (city entity, category=capital_province)
 *      └─ Capital (city entity, category=capital_autonomous_community)
 */

import type { SpainEntity } from "./types";

// ---------------------------------------------------------------------------
// Autonomous Community Capitals
// ---------------------------------------------------------------------------

const CCAA_CAPITALS: SpainEntity[] = [
  {
    id: "ES-SVQ",
    name: "Sevilla",
    nameAlt: "Seville",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [37.3891, -5.9845],
    geometryKind: "point",
    parentId: "ES-AN",
  },
  {
    id: "ES-ZAZ",
    name: "Zaragoza",
    nameAlt: "Zaragoza",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [41.6488, -0.8891],
    geometryKind: "point",
    parentId: "ES-AR",
  },
  {
    id: "ES-OVD",
    name: "Oviedo",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [43.3614, -5.8593],
    geometryKind: "point",
    parentId: "ES-AS",
  },
  {
    id: "ES-PMI",
    name: "Palma",
    nameAlt: "Palma de Mallorca",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [39.5696, 2.6502],
    geometryKind: "point",
    parentId: "ES-IB",
  },
  {
    id: "ES-TCI",
    name: "Santa Cruz de Tenerife",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [28.4682, -16.2546],
    geometryKind: "point",
    parentId: "ES-CN",
  },
  {
    id: "ES-SDR",
    name: "Santander",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [43.4623, -3.8099],
    geometryKind: "point",
    parentId: "ES-CB",
  },
  {
    id: "ES-VLL",
    name: "Valladolid",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [41.6523, -4.7245],
    geometryKind: "point",
    parentId: "ES-CL",
  },
  {
    id: "ES-TOL",
    name: "Toledo",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [39.8628, -4.0273],
    geometryKind: "point",
    parentId: "ES-CM",
  },
  {
    id: "ES-BCN",
    name: "Barcelona",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [41.3851, 2.1734],
    geometryKind: "point",
    parentId: "ES-CT",
  },
  {
    id: "ES-VLC",
    name: "València",
    nameAlt: "Valencia",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [39.4699, -0.3763],
    geometryKind: "point",
    parentId: "ES-VC",
  },
  {
    id: "ES-MJV",
    name: "Mérida",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [38.9166, -6.3407],
    geometryKind: "point",
    parentId: "ES-EX",
  },
  {
    id: "ES-SCQ",
    name: "Santiago de Compostela",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [42.8782, -8.5448],
    geometryKind: "point",
    parentId: "ES-GA",
  },
  {
    id: "ES-MAD",
    name: "Madrid",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [40.4168, -3.7038],
    geometryKind: "point",
    parentId: "ES-MD",
  },
  {
    id: "ES-MJU",
    name: "Murcia",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [37.9922, -1.1307],
    geometryKind: "point",
    parentId: "ES-MC",
  },
  {
    id: "ES-PNA",
    name: "Pamplona",
    nameAlt: "Iruña",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [42.8125, -1.6458],
    geometryKind: "point",
    parentId: "ES-NC",
  },
  {
    id: "ES-VIT",
    name: "Vitoria-Gasteiz",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [42.8467, -2.6726],
    geometryKind: "point",
    parentId: "ES-PV",
  },
  {
    id: "ES-RJL",
    name: "Logroño",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [42.465, -2.4456],
    geometryKind: "point",
    parentId: "ES-RI",
  },
  {
    id: "ES-CEU",
    name: "Ceuta",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [35.8894, -5.3213],
    geometryKind: "point",
    parentId: "ES-CE",
  },
  {
    id: "ES-MEL",
    name: "Melilla",
    domain: "spain",
    category: "capital_autonomous_community",
    coordinates: [35.2923, -2.9381],
    geometryKind: "point",
    parentId: "ES-ML",
  },
];

// ---------------------------------------------------------------------------
// Autonomous Communities (17 + 2 autonomous cities)
// ---------------------------------------------------------------------------

export const SPAIN_CCAA: SpainEntity[] = [
  {
    id: "ES-AN",
    name: "Andalucía",
    nameAlt: "Andalusia",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [37.3891, -5.9845],
    geometryKind: "polygon",
    capitalId: "ES-SVQ",
    capital: "Sevilla",
    flagCode: "es-an",
    ineCode: "01",
  },
  {
    id: "ES-AR",
    name: "Aragón",
    nameAlt: "Aragon",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [41.6488, -0.8891],
    geometryKind: "polygon",
    capitalId: "ES-ZAZ",
    capital: "Zaragoza",
    flagCode: "es-ar",
    ineCode: "02",
  },
  {
    id: "ES-AS",
    name: "Principado de Asturias",
    nameAlt: "Asturias",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [43.3614, -5.8593],
    geometryKind: "polygon",
    capitalId: "ES-OVD",
    capital: "Oviedo",
    flagCode: "es-as",
    ineCode: "03",
  },
  {
    id: "ES-IB",
    name: "Illes Balears",
    nameAlt: "Islas Baleares",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [39.5696, 2.6502],
    geometryKind: "polygon",
    capitalId: "ES-PMI",
    capital: "Palma",
    flagCode: "es-ib",
    ineCode: "04",
  },
  {
    id: "ES-CN",
    name: "Canarias",
    nameAlt: "Canary Islands",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [28.4682, -16.2546],
    geometryKind: "polygon",
    capitalId: "ES-TCI",
    capital: "Santa Cruz de Tenerife",
    flagCode: "es-cn",
    ineCode: "05",
  },
  {
    id: "ES-CB",
    name: "Cantabria",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [43.4623, -3.8099],
    geometryKind: "polygon",
    capitalId: "ES-SDR",
    capital: "Santander",
    flagCode: "es-cb",
    ineCode: "06",
  },
  {
    id: "ES-CL",
    name: "Castilla y León",
    nameAlt: "Castile and León",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [41.6523, -4.7245],
    geometryKind: "polygon",
    capitalId: "ES-VLL",
    capital: "Valladolid",
    flagCode: "es-cl",
    ineCode: "07",
  },
  {
    id: "ES-CM",
    name: "Castilla-La Mancha",
    nameAlt: "Castile-La Mancha",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [39.8628, -4.0273],
    geometryKind: "polygon",
    capitalId: "ES-TOL",
    capital: "Toledo",
    flagCode: "es-cm",
    ineCode: "08",
  },
  {
    id: "ES-CT",
    name: "Catalunya",
    nameAlt: "Cataluña",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [41.3851, 2.1734],
    geometryKind: "polygon",
    capitalId: "ES-BCN",
    capital: "Barcelona",
    flagCode: "es-ct",
    ineCode: "09",
  },
  {
    id: "ES-VC",
    name: "Comunitat Valenciana",
    nameAlt: "Comunidad Valenciana",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [39.4699, -0.3763],
    geometryKind: "polygon",
    capitalId: "ES-VLC",
    capital: "València",
    flagCode: "es-vc",
    ineCode: "10",
  },
  {
    id: "ES-EX",
    name: "Extremadura",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [38.9166, -6.3407],
    geometryKind: "polygon",
    capitalId: "ES-MJV",
    capital: "Mérida",
    flagCode: "es-ex",
    ineCode: "11",
  },
  {
    id: "ES-GA",
    name: "Galicia",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [42.8782, -8.5448],
    geometryKind: "polygon",
    capitalId: "ES-SCQ",
    capital: "Santiago de Compostela",
    flagCode: "es-ga",
    ineCode: "12",
  },
  {
    id: "ES-MD",
    name: "Comunidad de Madrid",
    nameAlt: "Madrid",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [40.4168, -3.7038],
    geometryKind: "polygon",
    capitalId: "ES-MAD",
    capital: "Madrid",
    flagCode: "es-md",
    ineCode: "13",
  },
  {
    id: "ES-MC",
    name: "Región de Murcia",
    nameAlt: "Murcia",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [37.9922, -1.1307],
    geometryKind: "polygon",
    capitalId: "ES-MJU",
    capital: "Murcia",
    flagCode: "es-mc",
    ineCode: "14",
  },
  {
    id: "ES-NC",
    name: "Comunidad Foral de Navarra",
    nameAlt: "Nafarroako Foru Komunitatea",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [42.8125, -1.6458],
    geometryKind: "polygon",
    capitalId: "ES-PNA",
    capital: "Pamplona",
    flagCode: "es-nc",
    ineCode: "15",
  },
  {
    id: "ES-PV",
    name: "País Vasco",
    nameAlt: "Euskadi",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [42.8467, -2.6726],
    geometryKind: "polygon",
    capitalId: "ES-VIT",
    capital: "Vitoria-Gasteiz",
    flagCode: "es-pv",
    ineCode: "16",
  },
  {
    id: "ES-RI",
    name: "La Rioja",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [42.465, -2.4456],
    geometryKind: "polygon",
    capitalId: "ES-RJL",
    capital: "Logroño",
    flagCode: "es-ri",
    ineCode: "17",
  },
  // Autonomous Cities
  {
    id: "ES-CE",
    name: "Ceuta",
    nameAlt: "Ciudad Autónoma de Ceuta",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [35.8894, -5.3213],
    geometryKind: "polygon",
    capitalId: "ES-CEU",
    capital: "Ceuta",
    flagCode: "es-ce",
    ineCode: "18",
  },
  {
    id: "ES-ML",
    name: "Melilla",
    nameAlt: "Ciudad Autónoma de Melilla",
    domain: "spain",
    category: "autonomous_community",
    coordinates: [35.2923, -2.9381],
    geometryKind: "polygon",
    capitalId: "ES-MEL",
    capital: "Melilla",
    flagCode: "es-ml",
    ineCode: "19",
  },
];

// ---------------------------------------------------------------------------
// Province Capitals (50 provinces → 50 capital cities)
// ---------------------------------------------------------------------------
// Note: some province capitals share an entity ID with a CCAA capital
// (e.g. ES-MAD for Madrid province and Comunidad de Madrid).
// These are not duplicated; capitals are referenced by ID across both levels.

const PROVINCE_CAPITALS: SpainEntity[] = [
  // --- País Vasco ---
  // Araba/Álava: capital is Vitoria-Gasteiz (same entity as PV CCAA capital ES-VIT)
  {
    id: "ES-ABE",
    name: "Albacete",
    domain: "spain",
    category: "capital_province",
    coordinates: [38.9955, -1.8558],
    geometryKind: "point",
    parentId: "ES-AB",
  },
  {
    id: "ES-ALC",
    name: "Alacant",
    nameAlt: "Alicante",
    domain: "spain",
    category: "capital_province",
    coordinates: [38.3452, -0.4815],
    geometryKind: "point",
    parentId: "ES-A",
  },
  {
    id: "ES-ALA",
    name: "Almería",
    domain: "spain",
    category: "capital_province",
    coordinates: [36.834, -2.4637],
    geometryKind: "point",
    parentId: "ES-AL",
  },
  {
    id: "ES-AVI",
    name: "Ávila",
    domain: "spain",
    category: "capital_province",
    coordinates: [40.6565, -4.6814],
    geometryKind: "point",
    parentId: "ES-AV",
  },
  {
    id: "ES-BJZ",
    name: "Badajoz",
    domain: "spain",
    category: "capital_province",
    coordinates: [38.8794, -6.9706],
    geometryKind: "point",
    parentId: "ES-BA",
  },
  // Illes Balears province: capital = Palma (same entity as IB CCAA capital ES-PMI)
  // Barcelona province: capital = Barcelona (same entity as CT CCAA capital ES-BCN)
  {
    id: "ES-BUO",
    name: "Burgos",
    domain: "spain",
    category: "capital_province",
    coordinates: [42.344, -3.697],
    geometryKind: "point",
    parentId: "ES-BU",
  },
  {
    id: "ES-CAC",
    name: "Cáceres",
    domain: "spain",
    category: "capital_province",
    coordinates: [39.4752, -6.3724],
    geometryKind: "point",
    parentId: "ES-CC",
  },
  {
    id: "ES-CDZ",
    name: "Cádiz",
    domain: "spain",
    category: "capital_province",
    coordinates: [36.5271, -6.2886],
    geometryKind: "point",
    parentId: "ES-CA",
  },
  {
    id: "ES-CST",
    name: "Castelló",
    nameAlt: "Castellón",
    domain: "spain",
    category: "capital_province",
    coordinates: [39.9864, -0.0513],
    geometryKind: "point",
    parentId: "ES-CS",
  },
  {
    id: "ES-CRR",
    name: "Ciudad Real",
    domain: "spain",
    category: "capital_province",
    coordinates: [38.9848, -3.9274],
    geometryKind: "point",
    parentId: "ES-CR",
  },
  {
    id: "ES-COR",
    name: "Córdoba",
    domain: "spain",
    category: "capital_province",
    coordinates: [37.8882, -4.7794],
    geometryKind: "point",
    parentId: "ES-CO",
  },
  {
    id: "ES-LCG",
    name: "A Coruña",
    domain: "spain",
    category: "capital_province",
    coordinates: [43.3623, -8.4115],
    geometryKind: "point",
    parentId: "ES-C",
  },
  {
    id: "ES-CUE",
    name: "Cuenca",
    domain: "spain",
    category: "capital_province",
    coordinates: [40.0704, -2.1374],
    geometryKind: "point",
    parentId: "ES-CU",
  },
  {
    id: "ES-GRO",
    name: "Girona",
    nameAlt: "Gerona",
    domain: "spain",
    category: "capital_province",
    coordinates: [41.9818, 2.8241],
    geometryKind: "point",
    parentId: "ES-GI",
  },
  {
    id: "ES-GRX",
    name: "Granada",
    domain: "spain",
    category: "capital_province",
    coordinates: [37.1773, -3.5986],
    geometryKind: "point",
    parentId: "ES-GR",
  },
  {
    id: "ES-GUA",
    name: "Guadalajara",
    domain: "spain",
    category: "capital_province",
    coordinates: [40.6331, -3.1622],
    geometryKind: "point",
    parentId: "ES-GU",
  },
  {
    id: "ES-EAS",
    name: "Donostia",
    nameAlt: "San Sebastián",
    domain: "spain",
    category: "capital_province",
    coordinates: [43.3183, -1.9812],
    geometryKind: "point",
    parentId: "ES-SS",
  },
  {
    id: "ES-HUV",
    name: "Huelva",
    domain: "spain",
    category: "capital_province",
    coordinates: [37.2614, -6.9447],
    geometryKind: "point",
    parentId: "ES-H",
  },
  {
    id: "ES-HSK",
    name: "Huesca",
    domain: "spain",
    category: "capital_province",
    coordinates: [42.1401, -0.4089],
    geometryKind: "point",
    parentId: "ES-HU",
  },
  {
    id: "ES-JAE",
    name: "Jaén",
    domain: "spain",
    category: "capital_province",
    coordinates: [37.7796, -3.7849],
    geometryKind: "point",
    parentId: "ES-J",
  },
  {
    id: "ES-LEN",
    name: "León",
    domain: "spain",
    category: "capital_province",
    coordinates: [42.5987, -5.5671],
    geometryKind: "point",
    parentId: "ES-LE",
  },
  {
    id: "ES-ILD",
    name: "Lleida",
    nameAlt: "Lérida",
    domain: "spain",
    category: "capital_province",
    coordinates: [41.6175, 0.62],
    geometryKind: "point",
    parentId: "ES-L",
  },
  // La Rioja province: capital = Logroño (same entity as RI CCAA capital ES-RJL)
  {
    id: "ES-LUG",
    name: "Lugo",
    domain: "spain",
    category: "capital_province",
    coordinates: [43.0097, -7.5569],
    geometryKind: "point",
    parentId: "ES-LU",
  },
  // Madrid province: capital = Madrid (same entity as MD CCAA capital ES-MAD)
  {
    id: "ES-AGP",
    name: "Málaga",
    domain: "spain",
    category: "capital_province",
    coordinates: [36.7213, -4.4213],
    geometryKind: "point",
    parentId: "ES-MA",
  },
  // Murcia province: capital = Murcia (same entity as MC CCAA capital ES-MJU)
  // Navarra province: capital = Pamplona (same entity as NC CCAA capital ES-PNA)
  {
    id: "ES-OUR",
    name: "Ourense",
    nameAlt: "Orense",
    domain: "spain",
    category: "capital_province",
    coordinates: [42.3364, -7.8641],
    geometryKind: "point",
    parentId: "ES-OR",
  },
  // Asturias province: capital = Oviedo (same entity as AS CCAA capital ES-OVD)
  {
    id: "ES-PLC",
    name: "Palencia",
    domain: "spain",
    category: "capital_province",
    coordinates: [42.0096, -4.5288],
    geometryKind: "point",
    parentId: "ES-P",
  },
  {
    id: "ES-LPA",
    name: "Las Palmas de Gran Canaria",
    domain: "spain",
    category: "capital_province",
    coordinates: [28.1235, -15.4366],
    geometryKind: "point",
    parentId: "ES-GC",
  },
  {
    id: "ES-POY",
    name: "Pontevedra",
    domain: "spain",
    category: "capital_province",
    coordinates: [42.4336, -8.6477],
    geometryKind: "point",
    parentId: "ES-PO",
  },
  {
    id: "ES-SAL",
    name: "Salamanca",
    domain: "spain",
    category: "capital_province",
    coordinates: [40.9701, -5.6635],
    geometryKind: "point",
    parentId: "ES-SA",
  },
  // Santa Cruz de Tenerife province: capital = Santa Cruz de Tenerife (same as CN CCAA capital ES-TCI)
  // Cantabria province: capital = Santander (same entity as CB CCAA capital ES-SDR)
  {
    id: "ES-SEG",
    name: "Segovia",
    domain: "spain",
    category: "capital_province",
    coordinates: [40.9496, -4.1225],
    geometryKind: "point",
    parentId: "ES-SG",
  },
  // Sevilla province: capital = Sevilla (same entity as AN CCAA capital ES-SVQ)
  {
    id: "ES-SOR",
    name: "Soria",
    domain: "spain",
    category: "capital_province",
    coordinates: [41.7635, -2.4648],
    geometryKind: "point",
    parentId: "ES-SO",
  },
  {
    id: "ES-TAR",
    name: "Tarragona",
    domain: "spain",
    category: "capital_province",
    coordinates: [41.1187, 1.2445],
    geometryKind: "point",
    parentId: "ES-T",
  },
  {
    id: "ES-TEU",
    name: "Teruel",
    domain: "spain",
    category: "capital_province",
    coordinates: [40.3456, -1.1065],
    geometryKind: "point",
    parentId: "ES-TE",
  },
  // Toledo province: capital = Toledo (same entity as CM CCAA capital ES-TOL)
  // Valencia province: capital = València (same entity as VC CCAA capital ES-VLC)
  // Valladolid province: capital = Valladolid (same entity as CL CCAA capital ES-VLL)
  {
    id: "ES-BIO",
    name: "Bilbao",
    domain: "spain",
    category: "capital_province",
    coordinates: [43.263, -2.935],
    geometryKind: "point",
    parentId: "ES-BI",
  },
  {
    id: "ES-ZAM",
    name: "Zamora",
    domain: "spain",
    category: "capital_province",
    coordinates: [41.5028, -5.7446],
    geometryKind: "point",
    parentId: "ES-ZA",
  },
  // Zaragoza province: capital = Zaragoza (same entity as AR CCAA capital ES-ZAZ)
];

// ---------------------------------------------------------------------------
// Provinces (50)
// ---------------------------------------------------------------------------

export const SPAIN_PROVINCES: SpainEntity[] = [
  // --- Andalucía (ES-AN) ---
  {
    id: "ES-AL",
    name: "Almería",
    domain: "spain",
    category: "province",
    coordinates: [36.834, -2.4637],
    geometryKind: "polygon",
    parentId: "ES-AN",
    capitalId: "ES-ALA",
    capital: "Almería",
    ineCode: "04",
  },
  {
    id: "ES-CA",
    name: "Cádiz",
    domain: "spain",
    category: "province",
    coordinates: [36.5271, -6.2886],
    geometryKind: "polygon",
    parentId: "ES-AN",
    capitalId: "ES-CDZ",
    capital: "Cádiz",
    ineCode: "11",
  },
  {
    id: "ES-CO",
    name: "Córdoba",
    domain: "spain",
    category: "province",
    coordinates: [37.8882, -4.7794],
    geometryKind: "polygon",
    parentId: "ES-AN",
    capitalId: "ES-COR",
    capital: "Córdoba",
    ineCode: "14",
  },
  {
    id: "ES-GR",
    name: "Granada",
    domain: "spain",
    category: "province",
    coordinates: [37.1773, -3.5986],
    geometryKind: "polygon",
    parentId: "ES-AN",
    capitalId: "ES-GRX",
    capital: "Granada",
    ineCode: "18",
  },
  {
    id: "ES-H",
    name: "Huelva",
    domain: "spain",
    category: "province",
    coordinates: [37.2614, -6.9447],
    geometryKind: "polygon",
    parentId: "ES-AN",
    capitalId: "ES-HUV",
    capital: "Huelva",
    ineCode: "21",
  },
  {
    id: "ES-J",
    name: "Jaén",
    domain: "spain",
    category: "province",
    coordinates: [37.7796, -3.7849],
    geometryKind: "polygon",
    parentId: "ES-AN",
    capitalId: "ES-JAE",
    capital: "Jaén",
    ineCode: "23",
  },
  {
    id: "ES-MA",
    name: "Málaga",
    domain: "spain",
    category: "province",
    coordinates: [36.7213, -4.4213],
    geometryKind: "polygon",
    parentId: "ES-AN",
    capitalId: "ES-AGP",
    capital: "Málaga",
    ineCode: "29",
  },
  {
    id: "ES-SE",
    name: "Sevilla",
    domain: "spain",
    category: "province",
    coordinates: [37.3891, -5.9845],
    geometryKind: "polygon",
    parentId: "ES-AN",
    capitalId: "ES-SVQ",
    capital: "Sevilla",
    ineCode: "41",
  },
  // --- Aragón (ES-AR) ---
  {
    id: "ES-HU",
    name: "Huesca",
    domain: "spain",
    category: "province",
    coordinates: [42.1401, -0.4089],
    geometryKind: "polygon",
    parentId: "ES-AR",
    capitalId: "ES-HSK",
    capital: "Huesca",
    ineCode: "22",
  },
  {
    id: "ES-TE",
    name: "Teruel",
    domain: "spain",
    category: "province",
    coordinates: [40.3456, -1.1065],
    geometryKind: "polygon",
    parentId: "ES-AR",
    capitalId: "ES-TEU",
    capital: "Teruel",
    ineCode: "44",
  },
  {
    id: "ES-Z",
    name: "Zaragoza",
    domain: "spain",
    category: "province",
    coordinates: [41.6488, -0.8891],
    geometryKind: "polygon",
    parentId: "ES-AR",
    capitalId: "ES-ZAZ",
    capital: "Zaragoza",
    ineCode: "50",
  },
  // --- Asturias (ES-AS) ---
  {
    id: "ES-O",
    name: "Asturias",
    domain: "spain",
    category: "province",
    coordinates: [43.3614, -5.8593],
    geometryKind: "polygon",
    parentId: "ES-AS",
    capitalId: "ES-OVD",
    capital: "Oviedo",
    ineCode: "33",
  },
  // --- Illes Balears (ES-IB) ---
  {
    id: "ES-PM",
    name: "Illes Balears",
    nameAlt: "Islas Baleares",
    domain: "spain",
    category: "province",
    coordinates: [39.5696, 2.6502],
    geometryKind: "polygon",
    parentId: "ES-IB",
    capitalId: "ES-PMI",
    capital: "Palma",
    ineCode: "07",
  },
  // --- Canarias (ES-CN) ---
  {
    id: "ES-GC",
    name: "Las Palmas",
    domain: "spain",
    category: "province",
    coordinates: [28.1235, -15.4366],
    geometryKind: "polygon",
    parentId: "ES-CN",
    capitalId: "ES-LPA",
    capital: "Las Palmas de Gran Canaria",
    ineCode: "35",
  },
  {
    id: "ES-TF",
    name: "Santa Cruz de Tenerife",
    domain: "spain",
    category: "province",
    coordinates: [28.4682, -16.2546],
    geometryKind: "polygon",
    parentId: "ES-CN",
    capitalId: "ES-TCI",
    capital: "Santa Cruz de Tenerife",
    ineCode: "38",
  },
  // --- Cantabria (ES-CB) ---
  {
    id: "ES-S",
    name: "Cantabria",
    domain: "spain",
    category: "province",
    coordinates: [43.4623, -3.8099],
    geometryKind: "polygon",
    parentId: "ES-CB",
    capitalId: "ES-SDR",
    capital: "Santander",
    ineCode: "39",
  },
  // --- Castilla y León (ES-CL) ---
  {
    id: "ES-AV",
    name: "Ávila",
    domain: "spain",
    category: "province",
    coordinates: [40.6565, -4.6814],
    geometryKind: "polygon",
    parentId: "ES-CL",
    capitalId: "ES-AVI",
    capital: "Ávila",
    ineCode: "05",
  },
  {
    id: "ES-BU",
    name: "Burgos",
    domain: "spain",
    category: "province",
    coordinates: [42.344, -3.697],
    geometryKind: "polygon",
    parentId: "ES-CL",
    capitalId: "ES-BUO",
    capital: "Burgos",
    ineCode: "09",
  },
  {
    id: "ES-LE",
    name: "León",
    domain: "spain",
    category: "province",
    coordinates: [42.5987, -5.5671],
    geometryKind: "polygon",
    parentId: "ES-CL",
    capitalId: "ES-LEN",
    capital: "León",
    ineCode: "24",
  },
  {
    id: "ES-P",
    name: "Palencia",
    domain: "spain",
    category: "province",
    coordinates: [42.0096, -4.5288],
    geometryKind: "polygon",
    parentId: "ES-CL",
    capitalId: "ES-PLC",
    capital: "Palencia",
    ineCode: "34",
  },
  {
    id: "ES-SA",
    name: "Salamanca",
    domain: "spain",
    category: "province",
    coordinates: [40.9701, -5.6635],
    geometryKind: "polygon",
    parentId: "ES-CL",
    capitalId: "ES-SAL",
    capital: "Salamanca",
    ineCode: "37",
  },
  {
    id: "ES-SG",
    name: "Segovia",
    domain: "spain",
    category: "province",
    coordinates: [40.9496, -4.1225],
    geometryKind: "polygon",
    parentId: "ES-CL",
    capitalId: "ES-SEG",
    capital: "Segovia",
    ineCode: "40",
  },
  {
    id: "ES-SO",
    name: "Soria",
    domain: "spain",
    category: "province",
    coordinates: [41.7635, -2.4648],
    geometryKind: "polygon",
    parentId: "ES-CL",
    capitalId: "ES-SOR",
    capital: "Soria",
    ineCode: "42",
  },
  {
    id: "ES-VA",
    name: "Valladolid",
    domain: "spain",
    category: "province",
    coordinates: [41.6523, -4.7245],
    geometryKind: "polygon",
    parentId: "ES-CL",
    capitalId: "ES-VLL",
    capital: "Valladolid",
    ineCode: "47",
  },
  {
    id: "ES-ZA",
    name: "Zamora",
    domain: "spain",
    category: "province",
    coordinates: [41.5028, -5.7446],
    geometryKind: "polygon",
    parentId: "ES-CL",
    capitalId: "ES-ZAM",
    capital: "Zamora",
    ineCode: "49",
  },
  // --- Castilla-La Mancha (ES-CM) ---
  {
    id: "ES-AB",
    name: "Albacete",
    domain: "spain",
    category: "province",
    coordinates: [38.9955, -1.8558],
    geometryKind: "polygon",
    parentId: "ES-CM",
    capitalId: "ES-ABE",
    capital: "Albacete",
    ineCode: "02",
  },
  {
    id: "ES-CR",
    name: "Ciudad Real",
    domain: "spain",
    category: "province",
    coordinates: [38.9848, -3.9274],
    geometryKind: "polygon",
    parentId: "ES-CM",
    capitalId: "ES-CRR",
    capital: "Ciudad Real",
    ineCode: "13",
  },
  {
    id: "ES-CU",
    name: "Cuenca",
    domain: "spain",
    category: "province",
    coordinates: [40.0704, -2.1374],
    geometryKind: "polygon",
    parentId: "ES-CM",
    capitalId: "ES-CUE",
    capital: "Cuenca",
    ineCode: "16",
  },
  {
    id: "ES-GU",
    name: "Guadalajara",
    domain: "spain",
    category: "province",
    coordinates: [40.6331, -3.1622],
    geometryKind: "polygon",
    parentId: "ES-CM",
    capitalId: "ES-GUA",
    capital: "Guadalajara",
    ineCode: "19",
  },
  {
    id: "ES-TO",
    name: "Toledo",
    domain: "spain",
    category: "province",
    coordinates: [39.8628, -4.0273],
    geometryKind: "polygon",
    parentId: "ES-CM",
    capitalId: "ES-TOL",
    capital: "Toledo",
    ineCode: "45",
  },
  // --- Catalunya (ES-CT) ---
  {
    id: "ES-B",
    name: "Barcelona",
    domain: "spain",
    category: "province",
    coordinates: [41.3851, 2.1734],
    geometryKind: "polygon",
    parentId: "ES-CT",
    capitalId: "ES-BCN",
    capital: "Barcelona",
    ineCode: "08",
  },
  {
    id: "ES-GI",
    name: "Girona",
    nameAlt: "Gerona",
    domain: "spain",
    category: "province",
    coordinates: [41.9818, 2.8241],
    geometryKind: "polygon",
    parentId: "ES-CT",
    capitalId: "ES-GRO",
    capital: "Girona",
    ineCode: "17",
  },
  {
    id: "ES-L",
    name: "Lleida",
    nameAlt: "Lérida",
    domain: "spain",
    category: "province",
    coordinates: [41.6175, 0.62],
    geometryKind: "polygon",
    parentId: "ES-CT",
    capitalId: "ES-ILD",
    capital: "Lleida",
    ineCode: "25",
  },
  {
    id: "ES-T",
    name: "Tarragona",
    domain: "spain",
    category: "province",
    coordinates: [41.1187, 1.2445],
    geometryKind: "polygon",
    parentId: "ES-CT",
    capitalId: "ES-TAR",
    capital: "Tarragona",
    ineCode: "43",
  },
  // --- Comunitat Valenciana (ES-VC) ---
  {
    id: "ES-A",
    name: "Alacant",
    nameAlt: "Alicante",
    domain: "spain",
    category: "province",
    coordinates: [38.3452, -0.4815],
    geometryKind: "polygon",
    parentId: "ES-VC",
    capitalId: "ES-ALC",
    capital: "Alacant",
    ineCode: "03",
  },
  {
    id: "ES-CS",
    name: "Castelló",
    nameAlt: "Castellón",
    domain: "spain",
    category: "province",
    coordinates: [39.9864, -0.0513],
    geometryKind: "polygon",
    parentId: "ES-VC",
    capitalId: "ES-CST",
    capital: "Castelló",
    ineCode: "12",
  },
  {
    id: "ES-V",
    name: "València",
    nameAlt: "Valencia",
    domain: "spain",
    category: "province",
    coordinates: [39.4699, -0.3763],
    geometryKind: "polygon",
    parentId: "ES-VC",
    capitalId: "ES-VLC",
    capital: "València",
    ineCode: "46",
  },
  // --- Extremadura (ES-EX) ---
  {
    id: "ES-BA",
    name: "Badajoz",
    domain: "spain",
    category: "province",
    coordinates: [38.8794, -6.9706],
    geometryKind: "polygon",
    parentId: "ES-EX",
    capitalId: "ES-BJZ",
    capital: "Badajoz",
    ineCode: "06",
  },
  {
    id: "ES-CC",
    name: "Cáceres",
    domain: "spain",
    category: "province",
    coordinates: [39.4752, -6.3724],
    geometryKind: "polygon",
    parentId: "ES-EX",
    capitalId: "ES-CAC",
    capital: "Cáceres",
    ineCode: "10",
  },
  // --- Galicia (ES-GA) ---
  {
    id: "ES-C",
    name: "A Coruña",
    domain: "spain",
    category: "province",
    coordinates: [43.3623, -8.4115],
    geometryKind: "polygon",
    parentId: "ES-GA",
    capitalId: "ES-LCG",
    capital: "A Coruña",
    ineCode: "15",
  },
  {
    id: "ES-LU",
    name: "Lugo",
    domain: "spain",
    category: "province",
    coordinates: [43.0097, -7.5569],
    geometryKind: "polygon",
    parentId: "ES-GA",
    capitalId: "ES-LUG",
    capital: "Lugo",
    ineCode: "27",
  },
  {
    id: "ES-OR",
    name: "Ourense",
    nameAlt: "Orense",
    domain: "spain",
    category: "province",
    coordinates: [42.3364, -7.8641],
    geometryKind: "polygon",
    parentId: "ES-GA",
    capitalId: "ES-OUR",
    capital: "Ourense",
    ineCode: "32",
  },
  {
    id: "ES-PO",
    name: "Pontevedra",
    domain: "spain",
    category: "province",
    coordinates: [42.4336, -8.6477],
    geometryKind: "polygon",
    parentId: "ES-GA",
    capitalId: "ES-POY",
    capital: "Pontevedra",
    ineCode: "36",
  },
  // --- Comunidad de Madrid (ES-MD) ---
  {
    id: "ES-M",
    name: "Madrid",
    domain: "spain",
    category: "province",
    coordinates: [40.4168, -3.7038],
    geometryKind: "polygon",
    parentId: "ES-MD",
    capitalId: "ES-MAD",
    capital: "Madrid",
    ineCode: "28",
  },
  // --- Región de Murcia (ES-MC) ---
  {
    id: "ES-MU",
    name: "Murcia",
    domain: "spain",
    category: "province",
    coordinates: [37.9922, -1.1307],
    geometryKind: "polygon",
    parentId: "ES-MC",
    capitalId: "ES-MJU",
    capital: "Murcia",
    ineCode: "30",
  },
  // --- Comunidad Foral de Navarra (ES-NC) ---
  {
    id: "ES-NA",
    name: "Navarra",
    nameAlt: "Nafarroa",
    domain: "spain",
    category: "province",
    coordinates: [42.8125, -1.6458],
    geometryKind: "polygon",
    parentId: "ES-NC",
    capitalId: "ES-PNA",
    capital: "Pamplona",
    ineCode: "31",
  },
  // --- País Vasco (ES-PV) ---
  {
    id: "ES-VI",
    name: "Araba",
    nameAlt: "Álava",
    domain: "spain",
    category: "province",
    coordinates: [42.8467, -2.6726],
    geometryKind: "polygon",
    parentId: "ES-PV",
    capitalId: "ES-VIT",
    capital: "Vitoria-Gasteiz",
    ineCode: "01",
  },
  {
    id: "ES-BI",
    name: "Bizkaia",
    nameAlt: "Vizcaya",
    domain: "spain",
    category: "province",
    coordinates: [43.263, -2.935],
    geometryKind: "polygon",
    parentId: "ES-PV",
    capitalId: "ES-BIO",
    capital: "Bilbao",
    ineCode: "48",
  },
  {
    id: "ES-SS",
    name: "Gipuzkoa",
    nameAlt: "Guipúzcoa",
    domain: "spain",
    category: "province",
    coordinates: [43.3183, -1.9812],
    geometryKind: "polygon",
    parentId: "ES-PV",
    capitalId: "ES-EAS",
    capital: "Donostia",
    ineCode: "20",
  },
  // --- La Rioja (ES-RI) ---
  {
    id: "ES-LO",
    name: "La Rioja",
    domain: "spain",
    category: "province",
    coordinates: [42.465, -2.4456],
    geometryKind: "polygon",
    parentId: "ES-RI",
    capitalId: "ES-RJL",
    capital: "Logroño",
    ineCode: "26",
  },
];

// ---------------------------------------------------------------------------
// Public exports
// ---------------------------------------------------------------------------

export const SPAIN_CAPITALS: SpainEntity[] = [...CCAA_CAPITALS, ...PROVINCE_CAPITALS];

/** All Spain entities: CCAA + autonomous cities + provinces + capitals */
export const SPAIN_ALL: SpainEntity[] = [
  ...SPAIN_CCAA,
  ...SPAIN_PROVINCES,
  ...SPAIN_CAPITALS,
];
