/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeedRouteImport } from './routes/speed'
import { Route as SpainRouteImport } from './routes/spain'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as NameRouteImport } from './routes/name'
import { Route as LocateRouteImport } from './routes/locate'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as FindRouteImport } from './routes/find'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CapitalsRouteImport } from './routes/capitals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAccountSyncRouteImport } from './routes/_authenticated/account.sync'

const SpeedRoute = SpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => rootRouteImport,
} as any)
const SpainRoute = SpainRouteImport.update({
  id: '/spain',
  path: '/spain',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRoute = NameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => rootRouteImport,
} as any)
const LocateRoute = LocateRouteImport.update({
  id: '/locate',
  path: '/locate',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalsRoute = CapitalsRouteImport.update({
  id: '/capitals',
  path: '/capitals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountSyncRoute =
  AuthenticatedAccountSyncRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capitals': typeof CapitalsRoute
  '/challenges': typeof ChallengesRoute
  '/explorer': typeof ExplorerRoute
  '/find': typeof FindRoute
  '/flags': typeof FlagsRoute
  '/locate': typeof LocateRoute
  '/name': typeof NameRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/spain': typeof SpainRoute
  '/speed': typeof SpeedRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/account/sync': typeof AuthenticatedAccountSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capitals': typeof CapitalsRoute
  '/challenges': typeof ChallengesRoute
  '/explorer': typeof ExplorerRoute
  '/find': typeof FindRoute
  '/flags': typeof FlagsRoute
  '/locate': typeof LocateRoute
  '/name': typeof NameRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/spain': typeof SpainRoute
  '/speed': typeof SpeedRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/account/sync': typeof AuthenticatedAccountSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/capitals': typeof CapitalsRoute
  '/challenges': typeof ChallengesRoute
  '/explorer': typeof ExplorerRoute
  '/find': typeof FindRoute
  '/flags': typeof FlagsRoute
  '/locate': typeof LocateRoute
  '/name': typeof NameRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/spain': typeof SpainRoute
  '/speed': typeof SpeedRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/account/sync': typeof AuthenticatedAccountSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/capitals'
    | '/challenges'
    | '/explorer'
    | '/find'
    | '/flags'
    | '/locate'
    | '/name'
    | '/progress'
    | '/reset-password'
    | '/review'
    | '/spain'
    | '/speed'
    | '/account'
    | '/account/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/capitals'
    | '/challenges'
    | '/explorer'
    | '/find'
    | '/flags'
    | '/locate'
    | '/name'
    | '/progress'
    | '/reset-password'
    | '/review'
    | '/spain'
    | '/speed'
    | '/account'
    | '/account/sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/capitals'
    | '/challenges'
    | '/explorer'
    | '/find'
    | '/flags'
    | '/locate'
    | '/name'
    | '/progress'
    | '/reset-password'
    | '/review'
    | '/spain'
    | '/speed'
    | '/_authenticated/account'
    | '/_authenticated/account/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CapitalsRoute: typeof CapitalsRoute
  ChallengesRoute: typeof ChallengesRoute
  ExplorerRoute: typeof ExplorerRoute
  FindRoute: typeof FindRoute
  FlagsRoute: typeof FlagsRoute
  LocateRoute: typeof LocateRoute
  NameRoute: typeof NameRoute
  ProgressRoute: typeof ProgressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRoute
  SpainRoute: typeof SpainRoute
  SpeedRoute: typeof SpeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speed': {
      id: '/speed'
      path: '/speed'
      fullPath: '/speed'
      preLoaderRoute: typeof SpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spain': {
      id: '/spain'
      path: '/spain'
      fullPath: '/spain'
      preLoaderRoute: typeof SpainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name': {
      id: '/name'
      path: '/name'
      fullPath: '/name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locate': {
      id: '/locate'
      path: '/locate'
      fullPath: '/locate'
      preLoaderRoute: typeof LocateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capitals': {
      id: '/capitals'
      path: '/capitals'
      fullPath: '/capitals'
      preLoaderRoute: typeof CapitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/sync': {
      id: '/_authenticated/account/sync'
      path: '/sync'
      fullPath: '/account/sync'
      preLoaderRoute: typeof AuthenticatedAccountSyncRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountSyncRoute: typeof AuthenticatedAccountSyncRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountSyncRoute: AuthenticatedAccountSyncRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CapitalsRoute: CapitalsRoute,
  ChallengesRoute: ChallengesRoute,
  ExplorerRoute: ExplorerRoute,
  FindRoute: FindRoute,
  FlagsRoute: FlagsRoute,
  LocateRoute: LocateRoute,
  NameRoute: NameRoute,
  ProgressRoute: ProgressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRoute,
  SpainRoute: SpainRoute,
  SpeedRoute: SpeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
